Modify Playwright workflow to run specific test and publish report
Updated Playwright test command to run specific test file and added a step to publish the test report.

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -22,7 +22,7 @@ jobs:
     - name: Install Playwright Browsers
       run: npx playwright install --with-deps
     - name: Run Playwright tests
-      run: npx playwright test
+      run: npx playwright test /tests/homepage.spec.ts
       continue-on-error: true
     - name: Upload Playwright Report to GitHub Pages
       if: ${{ !cancelled() }}
@@ -33,6 +33,10 @@ jobs:
       if: ${{ !cancelled() }}
       id: deployment
       uses: actions/deploy-pages@v4
-    - name: Add link to summary
-      if: ${{ !cancelled() }}
-      run: echo "📊 [View Playwright Report](https://mishmich.github.io/Toolshop---Playwright/)" >> $GITHUB_STEP_SUMMARY
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
